
CREATE TABLE appleLot (
 id INT NOT NULL AUTO_INCREMENT,
 company_name VARCHAR(256) NOT NULL,
 cultiver VARCHAR(256) NOT NULL,
 country_of_origin VARCHAR(256) NOT NULL,
 harvested_date DATE NOT NULL,
 weight INT NOT NULL,
 created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (id)
);
